services:
  php:
    build:
      context: ./server
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html/server  # Mount server folder to container
      - ./client:/var/www/html/client # Mount client folder to container
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount SQL initialization script
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
